/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CmpA {}
  interface CmpAAttributes extends StencilHTMLAttributes {}

  interface CmpB {}
  interface CmpBAttributes extends StencilHTMLAttributes {}

  interface CmpC {}
  interface CmpCAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'CmpA': Components.CmpA;
    'CmpB': Components.CmpB;
    'CmpC': Components.CmpC;
  }

  interface StencilIntrinsicElements {
    'cmp-a': Components.CmpAAttributes;
    'cmp-b': Components.CmpBAttributes;
    'cmp-c': Components.CmpCAttributes;
  }


  interface HTMLCmpAElement extends Components.CmpA, HTMLStencilElement {}
  var HTMLCmpAElement: {
    prototype: HTMLCmpAElement;
    new (): HTMLCmpAElement;
  };

  interface HTMLCmpBElement extends Components.CmpB, HTMLStencilElement {}
  var HTMLCmpBElement: {
    prototype: HTMLCmpBElement;
    new (): HTMLCmpBElement;
  };

  interface HTMLCmpCElement extends Components.CmpC, HTMLStencilElement {}
  var HTMLCmpCElement: {
    prototype: HTMLCmpCElement;
    new (): HTMLCmpCElement;
  };

  interface HTMLElementTagNameMap {
    'cmp-a': HTMLCmpAElement
    'cmp-b': HTMLCmpBElement
    'cmp-c': HTMLCmpCElement
  }

  interface ElementTagNameMap {
    'cmp-a': HTMLCmpAElement;
    'cmp-b': HTMLCmpBElement;
    'cmp-c': HTMLCmpCElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
